VERSION="2.2.1"

ACCOUNTS=["GB655IHUEKJ7STDVNIMXOAF6HUDIOC7EIRS5GOMG6ZQOVBZSJHBYVVLV"]

[DOCUMENTATION]
ORG_NAME="VALVE Corporation"
ORG_URL="https://www.valvestellar.com/"
ORG_DESCRIPTION="Valve Corporation, also known as Valve Software, is an American video game developer, publisher, and digital distribution company headquartered in Bellevue, Washington."
ORG_LOGO="https://www.valvestellar.com/valve.png"


[[CURRENCIES]]
code="VALVE"
status="live"
display_decimals=3
issuer="GB655IHUEKJ7STDVNIMXOAF6HUDIOC7EIRS5GOMG6ZQOVBZSJHBYVVLV"
anchor_asset_type="crypto"
name="VALVE Corp"
desc="Valve Corporation, also known as Valve Software, is an American video game developer, publisher, and digital distribution company headquartered in Bellevue, Washington."
image="https://www.valvestellar.com/valve.png"
